### ISSUE TITLE
multi lagan

### ISSUE THREAD

**Issue by mariemh23** [incertae-sedis/lagan#1]
Hello, 

I would like to use multi lagan but I can't find the executable

Could you help me?

**Comment by arendsee** [comment]
I don't really maintain this package. But I can give you some general advice.

Did you build the program? What operating system are you using? If you are on linux or Mac OS, you can do something like this:

```sh
git clone https://github.com/arendsee/lagan-fork
cd lagan-fork
make
```

After you build it, you should see a file called `mlagan`, which might be the executable you are looking for. Sorry, I hope this at least helps a little.

**Comment by arendsee** [comment]
@mariemh23 I've moved this repository to `incertae-sedis/lagan`, which is a little group I'm building for open source software that is not maintained.

**Comment by mariemh23** [comment]
@arendsee Thank you for your assistance

the mlagan file finally appeared when I make make. However, when I run the command:
mlagan genome1. fasta genome2. fasta genome3. fasta -out outputfile , I have this error message

sort: cannot read: +1: No such file or directory
Error from rechaos

Any idea what that might be?

**Comment by arendsee** [comment]
@mariemh23  Are you on a mac? I think the problem may be that they are using a non-portable shell expression in `rechaos.pl`.

**Comment by mariemh23** [comment]
no i'm working on a linux server

**Comment by arendsee** [comment]
@mariemh23 

They were using some truly ancient `sort` arguments. I've updated the `rechaos.pl` script. Now it might work. You can pull the program again and try it.

**Comment by arendsee** [comment]
@mariemh23 Does it work now?

**Comment by mariemh23** [comment]
@arendsee Yes, it seems to be working. I see anchors files appear. I am waiting to see if a multi fasta file will be generated

**Comment by arendsee** [comment]
Great, I'll close this issue then! Good luck

**Comment by mariemh23** [comment]
Thank you again
