### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by yjx1217** [incertae-sedis/lagan#3]
Hi arendse,

First of all, thank you very much for setting up this fork and fixing pre-existing issues in the original code (e.g. that related with getline() function).  In my attempt to compile lagan from this fork, I've encountered the following error. I was wondering if you can help me to diagnose the problem. 

Thanks in advance!

> 

jxyue@professorx:~/Programs/lagan> make
(cd src; make)
make[1]: Entering directory '/home/jxyue/Programs/lagan/src'
gcc -O3  -o ../anchors anchors.c skiplist.c
gcc -O3  -o ../chaos fchaos.c thrtrie.c skiplist.c global.c translate.c filebuffer.c -lm -DCHAOS__FLAG
In file included from /usr/include/string.h:635:0,
                 from filebuffer.c:3:
filebuffer.c: In function ‘FileRead’:
filebuffer.c:123:34: warning: implicit declaration of function ‘toupper’ [-Wimplicit-function-declaration]
     temp[i] = (strchr (alphabet, toupper ((char) i)) != 0) ?
                                  ^
gcc -O3  -o ../order order.c diagmatrix.c filebuffer.c
order.c: In function ‘doAlign’:
order.c:409:5: warning: implicit declaration of function ‘printMFAAlign’; did you mean ‘printBinAlign’? [-Wimplicit-function-declaration]
     printMFAAlign(seq1->lets, seq2->lets, a, seq1->name, seq2->name);
     ^~~~~~~~~~~~~
     printBinAlign
order.c:411:5: warning: implicit declaration of function ‘printXMFAAlign’; did you mean ‘printTextAlign’? [-Wimplicit-function-declaration]
     printXMFAAlign(seq1->lets, seq2->lets, a, seq1->name, seq2->name);
     ^~~~~~~~~~~~~~
     printTextAlign
In file included from /usr/include/string.h:635:0,
                 from filebuffer.c:3:
filebuffer.c: In function ‘FileRead’:
filebuffer.c:123:34: warning: implicit declaration of function ‘toupper’ [-Wimplicit-function-declaration]
     temp[i] = (strchr (alphabet, toupper ((char) i)) != 0) ?
                                  ^
gcc -O3  -o ../mlagan mlagan.c multial.c diagmatrix.c skiplist.c filebuffer.c -lm -DMULTIAL__FLAG
mlagan.c: In function ‘main’:
mlagan.c:1071:5: warning: implicit declaration of function ‘printXMFAAlign’; did you mean ‘printFASTAAlign’? [-Wimplicit-function-declaration]
     printXMFAAlign(outfile, final);
     ^~~~~~~~~~~~~~
     printFASTAAlign
multial.c:603:9: warning: ‘gapcache’ is static but used in inline function ‘openGap’ which is not static
   sav = gapcache[(v(ali->numseq - (alopen + ali->cnts[CNTS_CB][w]) + other->cnts[CNTS_GS][ow])) |
         ^~~~~~~~
multial.c:586:10: warning: ‘gapcache’ is static but used in inline function ‘contGap’ which is not static
   return gapcache[(v(other->cnts[CNTS_GS][ow])) |
          ^~~~~~~~
multial.c:581:10: warning: ‘gapcache’ is static but used in inline function ‘endGap2’ which is not static
   return gapcache[(v((a->numseq - a->cnts[CNTS_GS][ai] - a->cnts[CNTS_GC][ai]) + b->cnts[CNTS_GE][bi])<<12) |
          ^~~~~~~~
multial.c:576:10: warning: ‘gapcache’ is static but used in inline function ‘endGap1’ which is not static
   return gapcache[(v((b->numseq - b->cnts[CNTS_GS][bi] - b->cnts[CNTS_GC][bi]) + a->cnts[CNTS_GE][ai]) << 12) |
          ^~~~~~~~
multial.c:570:10: warning: ‘gapcache’ is static but used in inline function ‘endGap0’ which is not static
   return gapcache[(v(a->cnts[CNTS_GE][ai]+b->cnts[CNTS_GE][bi])<<12) |
          ^~~~~~~~
multial.c:563:10: warning: ‘matchcache’ is static but used in inline function ‘scoreOpp’ which is not static
   return matchcache[v(other->cnts[0][ow]) |
          ^~~~~~~~~~
multial.c:556:5: warning: ‘gapcache’ is static but used in inline function ‘matchscore’ which is not static
     gapcache[v(a->cnts[CNTS_GS][ai] + b->cnts[CNTS_GS][bi]) |
     ^~~~~~~~
multial.c:552:5: warning: ‘matchcache’ is static but used in inline function ‘matchscore’ which is not static
     matchcache[v(a->cnts[0][ai] + b->cnts[0][bi]) |
     ^~~~~~~~~~
In file included from /usr/include/string.h:635:0,
                 from filebuffer.c:3:
filebuffer.c: In function ‘FileRead’:
filebuffer.c:123:34: warning: implicit declaration of function ‘toupper’ [-Wimplicit-function-declaration]
     temp[i] = (strchr (alphabet, toupper ((char) i)) != 0) ?
                                  ^
gcc -O3  -o ../prolagan prolagan.c multial.c diagmatrix.c skiplist.c filebuffer.c -lm -DMULTIAL__FLAG
prolagan.c: In function ‘main’:
prolagan.c:1091:5: warning: implicit declaration of function ‘printXMFAAlign’; did you mean ‘printFASTAAlign’? [-Wimplicit-function-declaration]
     printXMFAAlign(outfile, final);
     ^~~~~~~~~~~~~~
     printFASTAAlign
multial.c:603:9: warning: ‘gapcache’ is static but used in inline function ‘openGap’ which is not static
   sav = gapcache[(v(ali->numseq - (alopen + ali->cnts[CNTS_CB][w]) + other->cnts[CNTS_GS][ow])) |
         ^~~~~~~~
multial.c:586:10: warning: ‘gapcache’ is static but used in inline function ‘contGap’ which is not static
   return gapcache[(v(other->cnts[CNTS_GS][ow])) |
          ^~~~~~~~
multial.c:581:10: warning: ‘gapcache’ is static but used in inline function ‘endGap2’ which is not static
   return gapcache[(v((a->numseq - a->cnts[CNTS_GS][ai] - a->cnts[CNTS_GC][ai]) + b->cnts[CNTS_GE][bi])<<12) |
          ^~~~~~~~
multial.c:576:10: warning: ‘gapcache’ is static but used in inline function ‘endGap1’ which is not static
   return gapcache[(v((b->numseq - b->cnts[CNTS_GS][bi] - b->cnts[CNTS_GC][bi]) + a->cnts[CNTS_GE][ai]) << 12) |
          ^~~~~~~~
multial.c:570:10: warning: ‘gapcache’ is static but used in inline function ‘endGap0’ which is not static
   return gapcache[(v(a->cnts[CNTS_GE][ai]+b->cnts[CNTS_GE][bi])<<12) |
          ^~~~~~~~
multial.c:563:10: warning: ‘matchcache’ is static but used in inline function ‘scoreOpp’ which is not static
   return matchcache[v(other->cnts[0][ow]) |
          ^~~~~~~~~~
multial.c:556:5: warning: ‘gapcache’ is static but used in inline function ‘matchscore’ which is not static
     gapcache[v(a->cnts[CNTS_GS][ai] + b->cnts[CNTS_GS][bi]) |
     ^~~~~~~~
multial.c:552:5: warning: ‘matchcache’ is static but used in inline function ‘matchscore’ which is not static
     matchcache[v(a->cnts[0][ai] + b->cnts[0][bi]) |
     ^~~~~~~~~~
In file included from /usr/include/string.h:635:0,
                 from filebuffer.c:3:
filebuffer.c: In function ‘FileRead’:
filebuffer.c:123:34: warning: implicit declaration of function ‘toupper’ [-Wimplicit-function-declaration]
     temp[i] = (strchr (alphabet, toupper ((char) i)) != 0) ?
                                  ^
gcc -O3  -o ../utils/bin2mf utils/bin2mf.c
gcc -O3  -o ../utils/bin2bl utils/bin2bl.c
gcc -O3  -o ../utils/cextract utils/cextract.c
gcc -O3  -o ../utils/cstat utils/cstat.c
utils/cstat.c: In function ‘cntlets’:
utils/cstat.c:51:10: warning: implicit declaration of function ‘isspace’ [-Wimplicit-function-declaration]
     if (!isspace(currchar)) {
          ^~~~~~~
utils/cstat.c:52:18: warning: implicit declaration of function ‘toupper’ [-Wimplicit-function-declaration]
       currchar = toupper(currchar);
                  ^~~~~~~
gcc -O3  -o ../utils/contigorder utils/contigorder.c
gcc -O3  -o ../utils/getbounds utils/getbounds.c
gcc -O3  -o ../utils/getlength utils/getlength.c
gcc -O3  -o ../utils/getoverlap utils/getoverlap.c
gcc -O3  -o ../utils/rc utils/rc.c
gcc -O3  -o ../utils/seqmerge utils/seqmerge.c
gcc -O3  -o ../utils/scorealign utils/scorealign.c -lm
gcc -O3  -o ../utils/scorecontigs utils/scorecontigs.c -lm
utils/scorecontigs.c: In function ‘cntlets’:
utils/scorecontigs.c:63:10: warning: implicit declaration of function ‘isspace’ [-Wimplicit-function-declaration]
     if (!isspace(currchar)) {
          ^~~~~~~
utils/scorecontigs.c:64:18: warning: implicit declaration of function ‘toupper’ [-Wimplicit-function-declaration]
       currchar = toupper(currchar);
                  ^~~~~~~
utils/scorecontigs.c:65:27: warning: implicit declaration of function ‘isalpha’ [-Wimplicit-function-declaration]
       if (!lettersonly || isalpha (currchar)){
                           ^~~~~~~
gcc -O3  -o ../utils/getcontigpos utils/getcontigpos.c
gcc -O3  -o ../utils/fa2xfa utils/fa2xfa.c
g++ -O3  -o ../utils/Glue utils/Glue.cpp
utils/Glue.cpp: In function ‘void calculateScoreMatrix(int)’:
utils/Glue.cpp:64:17: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   char *alpha = "ATCG";
                 ^~~~~~
utils/Glue.cpp:72:44: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     readScoreMatrix (NUCLEOTIDE_MATRIX_FILE);
                                            ^
g++ -O3  -o ../utils/dotplot utils/dotplot.cpp
gcc -O3  -o ../utils/overlay utils/overlay.c
utils/overlay.c: In function ‘read_align’:
utils/overlay.c:119:10: warning: implicit declaration of function ‘isspace’ [-Wimplicit-function-declaration]
     if (!isspace(currchar)) {
          ^~~~~~~
utils/overlay.c:120:19: warning: implicit declaration of function ‘toupper’ [-Wimplicit-function-declaration]
       checkchar = toupper(currchar);
                   ^~~~~~~
(cd glocal; make)
make[2]: Entering directory '/home/jxyue/Programs/lagan/src/glocal'
g++ -Wno-deprecated  -O3 -I./ -c glocal.cpp
g++ -Wno-deprecated  -O3 -I./ -c io.cpp
g++ -Wno-deprecated  -O3 -I./ -c rightinfluence.cpp
rightinfluence.cpp: In function ‘void initRI(RI*, long long int)’:
rightinfluence.cpp:21:2: error: reference to ‘end’ is ambiguous
  end.score = -2;
  ^~~
rightinfluence.cpp:3:18: note: candidates are: Fragment end
 Fragment origin, end;
                  ^~~
In file included from /usr/include/c++/7/vector:66:0,
                 from ./structs.h:6,
                 from ./rightinfluence.h:4,
                 from rightinfluence.cpp:1:
/usr/include/c++/7/bits/range_access.h:107:37: note:                 template<class _Tp> const _Tp* std::end(const std::valarray<_Tp>&)
   template<typename _Tp> const _Tp* end(const valarray<_Tp>&);
                                     ^~~
/usr/include/c++/7/bits/range_access.h:106:31: note:                 template<class _Tp> _Tp* std::end(std::valarray<_Tp>&)
   template<typename _Tp> _Tp* end(valarray<_Tp>&);
                               ^~~
/usr/include/c++/7/bits/range_access.h:97:5: note:                 template<class _Tp, long unsigned int _Nm> constexpr _Tp* std::end(_Tp (&)[_Nm])
     end(_Tp (&__arr)[_Nm])
     ^~~
/usr/include/c++/7/bits/range_access.h:78:5: note:                 template<class _Container> decltype (__cont.end()) std::end(const _Container&)
     end(const _Container& __cont) -> decltype(__cont.end())
     ^~~
/usr/include/c++/7/bits/range_access.h:68:5: note:                 template<class _Container> decltype (__cont.end()) std::end(_Container&)
     end(_Container& __cont) -> decltype(__cont.end())
     ^~~
In file included from /usr/include/c++/7/bits/stl_vector.h:63:0,
                 from /usr/include/c++/7/vector:64,
                 from ./structs.h:6,
                 from ./rightinfluence.h:4,
                 from rightinfluence.cpp:1:
/usr/include/c++/7/initializer_list:99:5: note:                 template<class _Tp> constexpr const _Tp* std::end(std::initializer_list<_Tp>)
     end(initializer_list<_Tp> __ils) noexcept
     ^~~
rightinfluence.cpp:22:22: error: reference to ‘end’ is ambiguous
  origin.totalScore = end.totalScore = 0;
                      ^~~
rightinfluence.cpp:3:18: note: candidates are: Fragment end
 Fragment origin, end;
                  ^~~
In file included from /usr/include/c++/7/vector:66:0,
                 from ./structs.h:6,
                 from ./rightinfluence.h:4,
                 from rightinfluence.cpp:1:
/usr/include/c++/7/bits/range_access.h:107:37: note:                 template<class _Tp> const _Tp* std::end(const std::valarray<_Tp>&)
   template<typename _Tp> const _Tp* end(const valarray<_Tp>&);
                                     ^~~
/usr/include/c++/7/bits/range_access.h:106:31: note:                 template<class _Tp> _Tp* std::end(std::valarray<_Tp>&)
   template<typename _Tp> _Tp* end(valarray<_Tp>&);
                               ^~~
/usr/include/c++/7/bits/range_access.h:97:5: note:                 template<class _Tp, long unsigned int _Nm> constexpr _Tp* std::end(_Tp (&)[_Nm])
     end(_Tp (&__arr)[_Nm])
     ^~~
/usr/include/c++/7/bits/range_access.h:78:5: note:                 template<class _Container> decltype (__cont.end()) std::end(const _Container&)
     end(const _Container& __cont) -> decltype(__cont.end())
     ^~~
/usr/include/c++/7/bits/range_access.h:68:5: note:                 template<class _Container> decltype (__cont.end()) std::end(_Container&)
     end(_Container& __cont) -> decltype(__cont.end())
     ^~~
In file included from /usr/include/c++/7/bits/stl_vector.h:63:0,
                 from /usr/include/c++/7/vector:64,
                 from ./structs.h:6,
                 from ./rightinfluence.h:4,
                 from rightinfluence.cpp:1:
/usr/include/c++/7/initializer_list:99:5: note:                 template<class _Tp> constexpr const _Tp* std::end(std::initializer_list<_Tp>)
     end(initializer_list<_Tp> __ils) noexcept
     ^~~
rightinfluence.cpp:25:2: error: reference to ‘end’ is ambiguous
  end.seq1End = 0; end.seq2End = 0;
  ^~~
rightinfluence.cpp:3:18: note: candidates are: Fragment end
 Fragment origin, end;
                  ^~~
In file included from /usr/include/c++/7/vector:66:0,
                 from ./structs.h:6,
                 from ./rightinfluence.h:4,
                 from rightinfluence.cpp:1:
/usr/include/c++/7/bits/range_access.h:107:37: note:                 template<class _Tp> const _Tp* std::end(const std::valarray<_Tp>&)
   template<typename _Tp> const _Tp* end(const valarray<_Tp>&);
                                     ^~~
/usr/include/c++/7/bits/range_access.h:106:31: note:                 template<class _Tp> _Tp* std::end(std::valarray<_Tp>&)
   template<typename _Tp> _Tp* end(valarray<_Tp>&);
                               ^~~
/usr/include/c++/7/bits/range_access.h:97:5: note:                 template<class _Tp, long unsigned int _Nm> constexpr _Tp* std::end(_Tp (&)[_Nm])
     end(_Tp (&__arr)[_Nm])
     ^~~
/usr/include/c++/7/bits/range_access.h:78:5: note:                 template<class _Container> decltype (__cont.end()) std::end(const _Container&)
     end(const _Container& __cont) -> decltype(__cont.end())
     ^~~
/usr/include/c++/7/bits/range_access.h:68:5: note:                 template<class _Container> decltype (__cont.end()) std::end(_Container&)
     end(_Container& __cont) -> decltype(__cont.end())
     ^~~
In file included from /usr/include/c++/7/bits/stl_vector.h:63:0,
                 from /usr/include/c++/7/vector:64,
                 from ./structs.h:6,
                 from ./rightinfluence.h:4,
                 from rightinfluence.cpp:1:
/usr/include/c++/7/initializer_list:99:5: note:                 template<class _Tp> constexpr const _Tp* std::end(std::initializer_list<_Tp>)
     end(initializer_list<_Tp> __ils) noexcept
     ^~~
rightinfluence.cpp:25:19: error: reference to ‘end’ is ambiguous
  end.seq1End = 0; end.seq2End = 0;
                   ^~~
rightinfluence.cpp:3:18: note: candidates are: Fragment end
 Fragment origin, end;
                  ^~~
In file included from /usr/include/c++/7/vector:66:0,
                 from ./structs.h:6,
                 from ./rightinfluence.h:4,
                 from rightinfluence.cpp:1:
/usr/include/c++/7/bits/range_access.h:107:37: note:                 template<class _Tp> const _Tp* std::end(const std::valarray<_Tp>&)
   template<typename _Tp> const _Tp* end(const valarray<_Tp>&);
                                     ^~~
/usr/include/c++/7/bits/range_access.h:106:31: note:                 template<class _Tp> _Tp* std::end(std::valarray<_Tp>&)
   template<typename _Tp> _Tp* end(valarray<_Tp>&);
                               ^~~
/usr/include/c++/7/bits/range_access.h:97:5: note:                 template<class _Tp, long unsigned int _Nm> constexpr _Tp* std::end(_Tp (&)[_Nm])
     end(_Tp (&__arr)[_Nm])
     ^~~
/usr/include/c++/7/bits/range_access.h:78:5: note:                 template<class _Container> decltype (__cont.end()) std::end(const _Container&)
     end(const _Container& __cont) -> decltype(__cont.end())
     ^~~
/usr/include/c++/7/bits/range_access.h:68:5: note:                 template<class _Container> decltype (__cont.end()) std::end(_Container&)
     end(_Container& __cont) -> decltype(__cont.end())
     ^~~
In file included from /usr/include/c++/7/bits/stl_vector.h:63:0,
                 from /usr/include/c++/7/vector:64,
                 from ./structs.h:6,
                 from ./rightinfluence.h:4,
                 from rightinfluence.cpp:1:
/usr/include/c++/7/initializer_list:99:5: note:                 template<class _Tp> constexpr const _Tp* std::end(std::initializer_list<_Tp>)
     end(initializer_list<_Tp> __ils) noexcept
     ^~~
rightinfluence.cpp:26:2: error: reference to ‘end’ is ambiguous
  end.seq1Start = 0; end.seq2Start = 0;
  ^~~
rightinfluence.cpp:3:18: note: candidates are: Fragment end
 Fragment origin, end;
                  ^~~
In file included from /usr/include/c++/7/vector:66:0,
                 from ./structs.h:6,
                 from ./rightinfluence.h:4,
                 from rightinfluence.cpp:1:
/usr/include/c++/7/bits/range_access.h:107:37: note:                 template<class _Tp> const _Tp* std::end(const std::valarray<_Tp>&)
   template<typename _Tp> const _Tp* end(const valarray<_Tp>&);
                                     ^~~
/usr/include/c++/7/bits/range_access.h:106:31: note:                 template<class _Tp> _Tp* std::end(std::valarray<_Tp>&)
   template<typename _Tp> _Tp* end(valarray<_Tp>&);
                               ^~~
/usr/include/c++/7/bits/range_access.h:97:5: note:                 template<class _Tp, long unsigned int _Nm> constexpr _Tp* std::end(_Tp (&)[_Nm])
     end(_Tp (&__arr)[_Nm])
     ^~~
/usr/include/c++/7/bits/range_access.h:78:5: note:                 template<class _Container> decltype (__cont.end()) std::end(const _Container&)
     end(const _Container& __cont) -> decltype(__cont.end())
     ^~~
/usr/include/c++/7/bits/range_access.h:68:5: note:                 template<class _Container> decltype (__cont.end()) std::end(_Container&)
     end(_Container& __cont) -> decltype(__cont.end())
     ^~~
In file included from /usr/include/c++/7/bits/stl_vector.h:63:0,
                 from /usr/include/c++/7/vector:64,
                 from ./structs.h:6,
                 from ./rightinfluence.h:4,
                 from rightinfluence.cpp:1:
/usr/include/c++/7/initializer_list:99:5: note:                 template<class _Tp> constexpr const _Tp* std::end(std::initializer_list<_Tp>)
     end(initializer_list<_Tp> __ils) noexcept
     ^~~
rightinfluence.cpp:26:21: error: reference to ‘end’ is ambiguous
  end.seq1Start = 0; end.seq2Start = 0;
                     ^~~
rightinfluence.cpp:3:18: note: candidates are: Fragment end
 Fragment origin, end;
                  ^~~
In file included from /usr/include/c++/7/vector:66:0,
                 from ./structs.h:6,
                 from ./rightinfluence.h:4,
                 from rightinfluence.cpp:1:
/usr/include/c++/7/bits/range_access.h:107:37: note:                 template<class _Tp> const _Tp* std::end(const std::valarray<_Tp>&)
   template<typename _Tp> const _Tp* end(const valarray<_Tp>&);
                                     ^~~
/usr/include/c++/7/bits/range_access.h:106:31: note:                 template<class _Tp> _Tp* std::end(std::valarray<_Tp>&)
   template<typename _Tp> _Tp* end(valarray<_Tp>&);
                               ^~~
/usr/include/c++/7/bits/range_access.h:97:5: note:                 template<class _Tp, long unsigned int _Nm> constexpr _Tp* std::end(_Tp (&)[_Nm])
     end(_Tp (&__arr)[_Nm])
     ^~~
/usr/include/c++/7/bits/range_access.h:78:5: note:                 template<class _Container> decltype (__cont.end()) std::end(const _Container&)
     end(const _Container& __cont) -> decltype(__cont.end())
     ^~~
/usr/include/c++/7/bits/range_access.h:68:5: note:                 template<class _Container> decltype (__cont.end()) std::end(_Container&)
     end(_Container& __cont) -> decltype(__cont.end())
     ^~~
In file included from /usr/include/c++/7/bits/stl_vector.h:63:0,
                 from /usr/include/c++/7/vector:64,
                 from ./structs.h:6,
                 from ./rightinfluence.h:4,
                 from rightinfluence.cpp:1:
/usr/include/c++/7/initializer_list:99:5: note:                 template<class _Tp> constexpr const _Tp* std::end(std::initializer_list<_Tp>)
     end(initializer_list<_Tp> __ils) noexcept
     ^~~
rightinfluence.cpp:31:34: error: reference to ‘end’ is ambiguous
     RightInfluence->act[+INF] = &end;
                                  ^~~
rightinfluence.cpp:3:18: note: candidates are: Fragment end
 Fragment origin, end;
                  ^~~
In file included from /usr/include/c++/7/vector:66:0,
                 from ./structs.h:6,
                 from ./rightinfluence.h:4,
                 from rightinfluence.cpp:1:
/usr/include/c++/7/bits/range_access.h:107:37: note:                 template<class _Tp> const _Tp* std::end(const std::valarray<_Tp>&)
   template<typename _Tp> const _Tp* end(const valarray<_Tp>&);
                                     ^~~
/usr/include/c++/7/bits/range_access.h:106:31: note:                 template<class _Tp> _Tp* std::end(std::valarray<_Tp>&)
   template<typename _Tp> _Tp* end(valarray<_Tp>&);
                               ^~~
/usr/include/c++/7/bits/range_access.h:97:5: note:                 template<class _Tp, long unsigned int _Nm> constexpr _Tp* std::end(_Tp (&)[_Nm])
     end(_Tp (&__arr)[_Nm])
     ^~~
/usr/include/c++/7/bits/range_access.h:78:5: note:                 template<class _Container> decltype (__cont.end()) std::end(const _Container&)
     end(const _Container& __cont) -> decltype(__cont.end())
     ^~~
/usr/include/c++/7/bits/range_access.h:68:5: note:                 template<class _Container> decltype (__cont.end()) std::end(_Container&)
     end(_Container& __cont) -> decltype(__cont.end())
     ^~~
In file included from /usr/include/c++/7/bits/stl_vector.h:63:0,
                 from /usr/include/c++/7/vector:64,
                 from ./structs.h:6,
                 from ./rightinfluence.h:4,
                 from rightinfluence.cpp:1:
/usr/include/c++/7/initializer_list:99:5: note:                 template<class _Tp> constexpr const _Tp* std::end(std::initializer_list<_Tp>)
     end(initializer_list<_Tp> __ils) noexcept
     ^~~
Makefile:13: recipe for target 'rightinfluence.o' failed
make[2]: *** [rightinfluence.o] Error 1
make[2]: Leaving directory '/home/jxyue/Programs/lagan/src/glocal'
Makefile:7: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/jxyue/Programs/lagan/src'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2

>

**Comment by arendsee** [comment]
@yjx1217 Thanks for the report. The error message says the variable `end` is ambiguous. Without looking any deeper into the problem, I changed the name from `end` to `endFrag`. This may fix the problem. It compiles on my system at least.

You can go ahead and pull the latest version and try compiling it again. Let me know how it goes. Good luck!

**Comment by yjx1217** [comment]
Hi @arendsee,

Many thanks for the quick reply and fix! It works! :-)

Best,
Jia-Xing
